version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    volumes:
      - postgres:/data/postgres
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: freshfood_dc
    ports:
      - '5432:5432'
    networks:
      - backend

  api-service:
    container_name: api-service
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/freshfood_dc
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - '80:80'
    networks:
      - backend
    depends_on:
      - postgres
  redis-container:
    image: docker.io/redis:7.2.3
    container_name: redis-container
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data/:/data
    networks:
      - backend
volumes:
  postgres:
networks:
  backend:
    driver: bridge